// AuthReducer actionTypes
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";


//productReducer actionTypes
export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";

export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS"
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";

//exerciseReducer actionTypes
export const EXERCISE_REQUEST = "EXERCISE_REQUEST";
export const EXERCISE_FAILURE = "EXERCISE_FAILURE";
export const EXERCISE_SUCCESS = "EXERCISE_SUCCESS";

export const EXERCISE_DELETE_SUCCESS = "EXERCISE_DELETE_SUCCESS"
export const EXERCISE_UPDATE_SUCCESS = "EXERCISE_UPDATE_SUCCESS"
export const EXERCISE_ADD_SUCCESS = "EXERCISE_ADD_SUCCESS";